feat: added formatBytes function
elninotech/uppload pull request #550
Opened 2021-02-27 00:51 UTC by cristianoap

This merge request closes https://github.com/elninotech/uppload/issues/402

2021-06-06 16:40 UTC, nicholasgriffintn requested changes

2021-06-06 16:40 UTC, nicholasgriffintn commented on src/helpers/utils.ts
> +
Comment for documentation would be good here, such as:

```
/**
 * Returns a formatted version of the bytes
 * @param bytes - The bytes to format
 * @param decimals - The number of decimals to show
 * @returns The formatted string
 */
```

2021-06-06 16:40 UTC, nicholasgriffintn commented on src/helpers/utils.ts
> +  const k: number = 1024;
Personally, I'd prefer variables to named, k, dm and i don't mean much and webpack minifies this anyway, so would be better if it was human readable IMO.

2021-08-07 17:07 UTC, cristianoap reviewed
@nicholasgriffintn updated according the comments

2021-08-12 13:21 UTC, phlegx commented
@cristianoap nice work!

2022-07-24 20:41 UTC, merged

2022-07-24 20:41 UTC, victorlap commented
Thanks!